name: tecksale_quanlybanhang
description: Quan ly ban hang thong minh.

publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.1.1
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.2.0
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.1.1
  url_launcher: ^6.2.5
  image: ^3.2.0
  flutter_blue_plus: ^1.31.13
  permission_handler: ^12.0.1
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  open_filex: ^4.3.2
  path: ^1.8.3
  device_info_plus: ^11.5.0
  confetti: ^0.8.0
  firebase_app_check: ^0.4.0
  gallery_saver_plus: ^3.2.8
  saver_gallery: ^4.0.0
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  share_plus: ^11.0.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.1
  mobile_scanner: ^3.5.0
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  audioplayers: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  collection: ^1.15.0 # Ghim phiên bản cũ hơn
  animate_do: ^3.3.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  math_expressions: ^2.4.0
  uuid: ^4.4.0
  # Hạ cấp file_saver để tương thích với 'collection'
  file_saver: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Hạ cấp lints để tương thích với Flutter 3.35.7
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.png"
  remove_alpha_ios: true
  min_sdk_android: 21