name: tecksale_quanlybanhang
description: Quan ly ban hang thong minh.

publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.0.0        # Cập nhật lên phiên bản mới nhất
  firebase_database: ^12.0.0    # Giữ nguyên, đã tương thích
  firebase_auth: ^6.0.0        # Cập nhật lên phiên bản mới nhất
  firebase_storage: ^13.0.0     # Cập nhật lên phiên bản mới nhất
  image_picker: ^1.1.1
  printing: ^5.13.1
  pdf: ^3.10.4
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.1.1
  url_launcher: ^6.2.5
  image: ^4.1.3
  flutter_blue_plus: ^1.31.13
  permission_handler: ^12.0.1
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  open_filex: ^4.3.2
  path: ^1.8.3
  device_info_plus: ^11.5.0
  confetti: ^0.8.0
  firebase_app_check: ^0.4.0
  gallery_saver_plus: ^3.2.8
  saver_gallery: ^4.0.0
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  share_plus: ^11.0.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.1
  mobile_scanner: ^3.5.0
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.png"
  remove_alpha_ios: true
  min_sdk_android: 21